# server:
#     port: 1205

#     servlet:
#         context-path: /tasty-town


# spring:
#     datasource:
#         url: jdbc:mysql://localhost/tasty-town    
#         username: root
#         password: Rakesh

#     jpa:
#         hibernate:
#             ddl-auto: update

#         show-sql: true        

# upload:
#     file:
#         dir: images   

# order:
#     delivery:
#         fee: 40

#     tax:
#         rate: 0.1         

server:
  port: 1205
  servlet:
    context-path: /tasty-town

spring:
  datasource:
    url: jdbc:mysql://localhost/tasty-town
    username: root
    password: Rakesh

#   profiles:
#     active: dev

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    
    properties:
      hibernate:
        format_sql: true

upload:
  file:
    dir: images

order:
  delivery:
    fee: 40

  tax:
    rate: 0.1