server:
    port: 1205

    servlet:
        context-path: /sms 
        # we have to use localhost:1205/sms before every api start

spring:
    application:
        name: sms

    datasource:
        url: jdbc:mysql://localhost/sms
        username: root
        password: Rakesh

    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true

        properties:
            hibernate:
                format_sql: true            

