# spring.application.name=jt-blog

# server.port = 1205

# spring.datasource.url=jdbc:mysql://localhost/blog
# spring.datasource.username=root
# spring.datasource.password=Rakesh

spring:
    application:
        name: jt-blogs

    # sql:
    #     init:
    #         mode: never

    jpa:
        hibernate:
            ddl-auto: update

            # ddl-auto modes:

            # create --> drop -> create [recommended for testing]
            # create-drop --> drop -> create -> drop  , used for testing to drop test data after testing
            # none --> does nothing [recommended for production]
            # update --> modify data or row of DB, if required add new column/modify column type, but never drop column to avoid deletion of sensitive info   [only recommended for development]
            # validate --> validate table with entity [recommended for production]



        show-sql: true    
        properties:
            hibernate:
                format_sql: true

    datasource:
        url: jdbc:mysql://localhost/blog?createDatabaseIfNotExist=true
        username: root
        password: Rakesh

server:
    port: 1205        